### ISSUE TITLE
Logins fail

### ISSUE THREAD

**Issue by wardmundy** [EspaceNetworks/pygooglevoice#5]
gvoice
Email address: working-gv-acct@gmail.com
Password: xoxo

Login failed. Retry?[Y/n]

**Comment by chris001** [comment]
From your forum post. After Retry (Yes), this error:
```
Login failed. Retry?[Y/n] y
Traceback (most recent call last):
  File "/usr/bin/gvoice", line 79, in <module>
    login()
  File "/usr/bin/gvoice", line 55, in login
    login(None, None, batch)
  File "/usr/bin/gvoice", line 49, in login
    voice.login(options.email,options.passwd)
  File "/usr/lib/python2.7/site-packages/googlevoice/voice.py", line 76, in login
    gxf = re.search(r"type=\"hidden\"\s+name=\"gxf\"\s+value=\"(.+)\"", content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by chris001** [comment]
I carefully diffed the code installed on my VM which works, and the `master` (default newest) version in this repo, and found no difference, except for some commented lines and commented notes, which I haven't uploaded to this repo.

Only thing I can think of is, do you have a burner GV account which you could change the password to something new, lend me the credentials in private message, and I'll use it to troubleshoot for a short time, then you can change your burner GV account pw back to your usual pw?

**Comment by wardmundy** [comment]
I'll be happy to do that. We're out of town for about a week so I'll have
to test one that fails when we get home. In the meantime, please send me
your email address. Mine is wardmundy [at] GMAIL. Thanks.
--wm

**Comment by chris001** [comment]
Sent! Thanks

**Comment by chris001** [comment]
For anyone with a similar login error!
The reason it failed to login was because the "DisplayUnlockCaptcha" ("DUC") had not been performed prior to running gvoice on this VM.
* Open https://accounts.google.com/DisplayUnlockCaptcha , click the button, and it should immediately let `gvoice` log in.
* TODO I also notice the code on github is not the absolute newest and needs updating. Several commands are crashing, which I've fixed locally.
* TODO Also there's a total lack of informative error messages - will add these.
* TODO Automatic handing of DUC - after all it's only a web page.

**Comment by chris001** [comment]
Yes, what "DisplayUnlockCaptcha" does is, for the NEXT login from a previously unknown device (identified by its MAC address and/or IP address), GV whitelists THAT IP address and/or MAC address, and allows the login to get in.
Most likely MAC address, although I haven't tested it, because mobile devices are constantly changing IP address as you roam around tto different cell towers and wifi hotspots, and keep the same MAC address.

**Comment by BobbyGR** [comment]
+1 @chris001 - After syncing up with the new code, and doing this DUC this is working perfectly.  

Thanks again for all of your guys hard work so I don't need to do it :)

**Comment by chris001** [comment]
@BobbyGR   You're quite welcome!  Keep us updated if any issues come up.

As a reminder to all of you out there using the software.  Many of you may not know that, if you would like to contribute to support my serious efforts to fix and develop this software further, you can make a contribution to help cover my running costs:
https://www.gofundme.com/espacenetworks-pygooglevoice
Thank you to everyone who will support. It's because of you that I can do this and make this software work again!
- Chris Coleman @ Espace Networks
