### ISSUE TITLE
Install Problem?  No module named 'voice'

### ISSUE THREAD

**Issue by andreawhitlock** [EspaceNetworks/pygooglevoice#9]
Sorry for the newbie problem.  I think maybe I have install problem as the gvoice script can't find the voice module.

I followed these steps:

cd /opt
git clone https://github.com/EspaceNetworks/pygooglevoice
cd pygooglevoice
sudo python setup.py install --record files.txt
sudo cp -p bin/gvoice /usr/bin/.
sudo pip install --upgrade BeautifulSoup

And I get this error trying to run gvoice:

[andrea@darius ~]$ gvoice
Traceback (most recent call last):
  File "/usr/local/bin/gvoice", line 5, in <module>
    from googlevoice.voice import Voice
  File "/usr/local/lib/python3.6/site-packages/googlevoice/__init__.py", line 17, in <module>
    from voice import Voice
ModuleNotFoundError: No module named 'voice'

**Comment by chris001** [comment]
Apologies for the delay!
Attempting to reproduce this issue... 
Which OS and OS version you running on your `darius` machine?

**Comment by andreawhitlock** [comment]
[andrea@darius ~]$ cat /etc/system-release
Fedora release 30 (Thirty)
[andrea@darius ~]$ cat /proc/version
Linux version 5.2.9-200.fc30.x86_64 (mockbuild@bkernel04.phx2.fedoraproject.org) (gcc version 9.1.1 20190503 (Red Hat 9.1.1-1) (GCC)) #1 SMP Fri Aug 16 21:37:45 UTC 2019
